hotfix/CP-6911-app-banner-copy-to-clipboard-does-not-copying-voucher-code
cleverpush/cleverpush-android-sdk pull request #162
Opened 2023-10-20 11:55 UTC by unnaticleverpush

App Banner: Copy To Clipboard does not copy voucher code

2023-10-20 12:02 UTC, gbhrdt requested changes

2023-10-20 12:02 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/service/NotificationService.java
> +    if (voucherCode != null && title.contains("{voucherCode}")) {
Move to util function. duplicated code.

2023-10-25 08:03 UTC, cpKevinrodriguesnobre approved these changes

2023-10-25 08:36 UTC, iboruch approved these changes

2023-10-26 08:46 UTC, gbhrdt requested changes

2023-10-26 08:46 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/service/NotificationService.java
> +  public String voucherCodeString(String text, String voucherCode) {
Duplicated code. Maybe put into some Utils class

2023-10-26 08:46 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/service/NotificationService.java
> +      e.printStackTrace();
Never use e.printStackTrace, use Log.e with out Tag

2023-10-26 08:46 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/service/NotificationService.java
> +  public String voucherCodeString(String text, String voucherCode) {
Also use a more speaking function name. e.g. replaceVoucherCodeString

2023-10-27 13:46 UTC, cpKevinrodriguesnobre approved these changes

2023-10-28 21:20 UTC, merged