hotfix/CP-8085-geo-fence-feature-does-not-work-follow-ups-dont-trigger
cleverpush/cleverpush-android-sdk pull request #220
Opened 2024-06-28 10:18 UTC by unnaticleverpush

ACCESS_BACKGROUND_LOCATION permission is needed starting from Android 10 (API level 29)

2024-06-28 10:35 UTC, gbhrdt requested changes

2024-06-28 10:35 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/CleverPush.java
> +        .setMessage("This app needs background location access to enable geofencing features. Please enable this permission in the app settings." +
Not translated

2024-06-28 14:29 UTC, cpKevinrodriguesnobre approved these changes

2024-07-02 18:00 UTC, gbhrdt requested changes

2024-07-02 18:00 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/CleverPush.java
> +        message = "Diese App benötigt Hintergrundzugriff auf den Standort, um Geofencing-Funktionen zu aktivieren. Bitte aktivieren Sie diese Berechtigung in den App-Einstellungen." +
Put translations into constants so we can easily extend to more translations in the future.
And please also put the existing translations we have from the SDK into this constant / class for getting the translated value.
So we can call something like `CPTranslations.get('locationPermissionDialog.title')` (pseudo code)

2024-07-05 07:05 UTC, cpKevinrodriguesnobre approved these changes

2024-07-11 14:53 UTC, merged