feature/CP-4745-android-support-app-banner-language-filter
cleverpush/cleverpush-android-sdk pull request #86
Opened 2022-10-19 11:02 UTC by jprajapati1996

CP-4745 - Added App banner languages

2022-10-19 19:58 UTC, gbhrdt requested changes

2022-10-19 19:58 UTC, gbhrdt commented on cleverpush/src/main/java/com/cleverpush/banner/models/Banner.java
> +    public List<String> getLanguages(){
space before {

2022-10-20 07:04 UTC, jprajapati1996 commented on cleverpush/src/main/java/com/cleverpush/banner/models/Banner.java
> +    public List<String> getLanguages(){
okay

2022-10-22 11:08 UTC, gbhrdt approved these changes

2022-11-03 12:21 UTC, merged